### ISSUE TITLE
WebHCatGroovy - Pig and Hive -> HTTP/1.1 500 Server Error on basic cluster

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/BigInsights-on-Apache-Hadoop#24]
Pig

```
christophers-MacBook-Pro:WebHCatGroovy snowch$ ./gradlew Pig
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:Pig
[Pig.groovy] Delete /user/snowch/test: 200
[Pig.groovy] Mkdir /user/snowch/test: 200
[Pig.groovy] Copy Pig query file to HDFS
[Pig.groovy] Copy data file to HDFS
Exception in thread "main" org.apache.hadoop.gateway.shell.HadoopException: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 500 Server Error
    at org.apache.hadoop.gateway.shell.AbstractRequest.now(AbstractRequest.java:72)
    at org.apache.hadoop.gateway.shell.AbstractRequest$now.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at Pig.run(Pig.groovy:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
    at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
    at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at Pig.main(Pig.groovy)
Caused by: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 500 Server Error
    at org.apache.hadoop.gateway.shell.Hadoop.executeNow(Hadoop.java:107)
    at org.apache.hadoop.gateway.shell.AbstractRequest.execute(AbstractRequest.java:47)
    at org.apache.hadoop.gateway.shell.job.Pig$Request.access$900(Pig.java:37)
    at org.apache.hadoop.gateway.shell.job.Pig$Request$1.call(Pig.java:81)
    at org.apache.hadoop.gateway.shell.job.Pig$Request$1.call(Pig.java:69)
    at org.apache.hadoop.gateway.shell.AbstractRequest.now(AbstractRequest.java:70)
    ... 21 more
:Pig FAILED
```

Hive

```
christophers-MacBook-Pro:WebHCatGroovy snowch$ ./gradlew Hive
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:Hive
[Hive.groovy] Delete /user/snowch/test: 200
[Hive.groovy] Mkdir /user/snowch/test: 200
[Hive.groovy] Copy Hive query file to HDFS
Exception in thread "main" org.apache.hadoop.gateway.shell.HadoopException: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 500 Server Error
    at org.apache.hadoop.gateway.shell.AbstractRequest.now(AbstractRequest.java:72)
    at org.apache.hadoop.gateway.shell.AbstractRequest$now.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at Hive.run(Hive.groovy:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
    at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
    at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at Hive.main(Hive.groovy)
Caused by: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 500 Server Error
    at org.apache.hadoop.gateway.shell.Hadoop.executeNow(Hadoop.java:107)
    at org.apache.hadoop.gateway.shell.AbstractRequest.execute(AbstractRequest.java:47)
    at org.apache.hadoop.gateway.shell.job.Hive$Request.access$700(Hive.java:37)
    at org.apache.hadoop.gateway.shell.job.Hive$Request$1.call(Hive.java:79)
    at org.apache.hadoop.gateway.shell.job.Hive$Request$1.call(Hive.java:69)
    at org.apache.hadoop.gateway.shell.AbstractRequest.now(AbstractRequest.java:70)
    ... 21 more
:Hive FAILED
```

**Comment by pregazzoni** [comment]
@snowch is this a 4.2 basic cluster? Looks like same issue we were seeing before.

Can you try to run:

```
curl -k -i -u biadmin https://<knox-host>:8443/gateway/default/templeton/v1/version 
```

Then, try sample test again.

**Comment by pregazzoni** [comment]
@snowch can you check on newly provisioned cluster. This should be fixed now as issue is due to webhcat configuration I believe.

**Comment by snowch** [comment]
I just received a different error on a newly provisioned 4.2 Basic cluster: 

```
Exception in thread "main" org.apache.hadoop.gateway.shell.HadoopException: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 404 Not Found
```

**Comment by pregazzoni** [comment]
What is entry or format you used for gateway URL?
