### ISSUE TITLE
OozieWorkflowSparkGroovy http 500 on Basic cluster

### ISSUE THREAD

**Issue by snowch** [IBM-Cloud/BigInsights-on-Apache-Hadoop#28]
```
OozieWorkflowSparkGroovy snowch$ ./gradlew Example
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:Example
[Example.groovy] Delete /user/snowch/test: 200
[Example.groovy] Mkdir /user/snowch/test: 200
[Example.groovy] Uploading jar file may take some time...
[Example.groovy] Put /user/snowch/test/input/FILE: 201
[Example.groovy] Put /user/snowch/test/lib/OozieWorkflowSparkGroovy.jar 201
[Example.groovy] Put /user/snowch/test/workflow.xml: 201
[Example.groovy] Downloading spark assembly jar file, may take some time...
[Example.groovy] Uploading spark assembly jar file to job lib dir, may take some time...
Exception in thread "main" org.apache.hadoop.gateway.shell.HadoopException: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 500 Server Error
	at org.apache.hadoop.gateway.shell.AbstractRequest.now(AbstractRequest.java:72)
	at org.apache.hadoop.gateway.shell.AbstractRequest$now.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at Example.run(Example.groovy:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at Example.main(Example.groovy)
Caused by: org.apache.hadoop.gateway.shell.ErrorResponse: HTTP/1.1 500 Server Error
	at org.apache.hadoop.gateway.shell.Hadoop.executeNow(Hadoop.java:107)
	at org.apache.hadoop.gateway.shell.AbstractRequest.execute(AbstractRequest.java:47)
	at org.apache.hadoop.gateway.shell.workflow.Submit$Request.access$500(Submit.java:38)
	at org.apache.hadoop.gateway.shell.workflow.Submit$Request$1.call(Submit.java:77)
	at org.apache.hadoop.gateway.shell.workflow.Submit$Request$1.call(Submit.java:64)
	at org.apache.hadoop.gateway.shell.AbstractRequest.now(AbstractRequest.java:70)
	... 21 more
:Example FAILED
```

**Comment by snowch** [comment]
This may have been because I provisioned the cluster without oozie.  The server capacity on bluemix is used up now so I'll have to wait until there is free capacity to try again.
